name: dart_balancer_example
description: Example app for dart_balancer package.
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  dart_balancer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
